# Generated by Django 4.2.9 on 2024-03-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_genre_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
