# Generated by Django 4.2.9 on 2024-03-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_movie_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
