# Generated by Django 4.2.9 on 2024-03-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favouritesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviefav',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='moviefav',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
